FROM ghcr.io/tl-its-umich-edu/udoit:v3.0.1

# https://documentation.its.umich.edu/node/2118
RUN useradd -g root -m -s /bin/bash -l -o -u 1000940000 www-root

# Switch Apache to Nginx
RUN apt-get install -y nginx && apt-get remove -y apache2

# Copy over the files
WORKDIR /var/www/html

COPY . .

# Composer isn't run for some reason
RUN composer install --no-dev


# Copy over the nginx config
COPY config/nginx_app.conf /etc/nginx/sites-available/default

CMD ["/usr/bin/supervisord", "-n", "-c", "/var/www/html/config/supervisord.conf"]
