services:
  nginx:
    image: nginx:stable-alpine
    container_name: udoit-nginx
    volumes:
        - ./docker/etc/nginx:/etc/nginx
        - ./docker/var/ssl:/var/ssl
        - .:/var/www/html
    ports:
        - "8000:80"
  # Uncomment this block and comment the next db block
  # to use MySQL instead of Postgres
  db:
    image: mysql:latest
    container_name: udoit-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udoit
      MYSQL_USER: udoit
      MYSQL_PASSWORD: udoit
    ports:
      - "3306:3306"
  php:
    container_name: udoit-php
    build:
      context: .
      dockerfile: docker/php81-fpm.Dockerfile
    volumes:
      - .:/var/www/html
volumes:
  web:
  dbdata:
