FROM ghcr.io/tl-its-umich-edu/udoit:v3.0.1

# https://documentation.its.umich.edu/node/2118
# RUN useradd -g root -m -s /bin/bash -l -o -u 1000940000 www-data && 
RUN chmod g+w /etc/passwd

# Switch Apache to Nginx
RUN apt-get install -y nginx && apt-get remove -y apache2

# Update nginx, change access.log
RUN sed -i 's/\/var\/log\/nginx\/access.log/\/dev\/stdout/g' /etc/nginx/nginx.conf && \
    # Chang error.log 
    sed -i 's/\/var\/log\/nginx\/error.log/\/dev\/stdout info/g' /etc/nginx/nginx.conf && \
    # Change pid location
    sed -i 's/\/run\/nginx.pid/\/tmp\/nginx.pid/g' /etc/nginx/nginx.conf && \
    # Delete user line
    sed -i '/^user/d' /etc/nginx/nginx.conf

# For nginx as non root
RUN mkdir /var/lib/nginx/body /var/lib/nginx/fastcgi /var/lib/nginx/proxy /var/lib/nginx/uwsgi /var/lib/nginx/scgi && \
    chown -R root:root /var/lib/nginx/ /var/log/nginx && chmod g+rw -R /var/lib/nginx /var/log/nginx

# Copy over the files
WORKDIR /var/www/html

# Copy over the nginx config
COPY config/nginx_app.conf /etc/nginx/sites-available/default

COPY . .

# Composer needs to run here, ideally only the file needed for composer would be copied and this would run before the previous statement
RUN composer install --no-dev

CMD ["/var/www/html/umich-start.sh"]
