[supervisord]
    user=www-data
    pidfile=/tmp/supervisord.pid

[program:php-fpm]
    command=php-fpm -F -R --force-stderr
    autostart=true
    autorestart=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

[program:nginx]
    command=/usr/sbin/nginx -g "daemon off;error_log /dev/stdout info;"
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
